#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: distutils3
#
Name     : pypi-rapidfuzz
Version  : 2.15.1
Release  : 8
URL      : https://files.pythonhosted.org/packages/44/19/a20bd17379cca3e0a63590a6473ecf6cdaa8351688de775afefffc701a79/rapidfuzz-2.15.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/44/19/a20bd17379cca3e0a63590a6473ecf6cdaa8351688de775afefffc701a79/rapidfuzz-2.15.1.tar.gz
Summary  : rapid fuzzy string matching
Group    : Development/Tools
License  : MIT
Requires: pypi-rapidfuzz-license = %{version}-%{release}
Requires: pypi-rapidfuzz-python = %{version}-%{release}
Requires: pypi-rapidfuzz-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
<h1 align="center">
<img src="https://raw.githubusercontent.com/maxbachmann/RapidFuzz/main/docs/img/RapidFuzz.svg?sanitize=true" alt="RapidFuzz" width="400">
</h1>
<h4 align="center">Rapid fuzzy string matching in Python and C++ using the Levenshtein Distance</h4>

%package license
Summary: license components for the pypi-rapidfuzz package.
Group: Default

%description license
license components for the pypi-rapidfuzz package.


%package python
Summary: python components for the pypi-rapidfuzz package.
Group: Default
Requires: pypi-rapidfuzz-python3 = %{version}-%{release}

%description python
python components for the pypi-rapidfuzz package.


%package python3
Summary: python3 components for the pypi-rapidfuzz package.
Group: Default
Requires: python3-core
Provides: pypi(rapidfuzz)

%description python3
python3 components for the pypi-rapidfuzz package.


%prep
%setup -q -n rapidfuzz-2.15.1
cd %{_builddir}/rapidfuzz-2.15.1
pushd ..
cp -a rapidfuzz-2.15.1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1681224848
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-rapidfuzz
cp %{_builddir}/rapidfuzz-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-rapidfuzz/943137af74d8ef1313354a6a6de0a4dc3ee4df8c || :
cp %{_builddir}/rapidfuzz-%{version}/extern/rapidfuzz-cpp/LICENSE %{buildroot}/usr/share/package-licenses/pypi-rapidfuzz/0375d56b18430f366cea90f3712664ccd180558c || :
cp %{_builddir}/rapidfuzz-%{version}/extern/taskflow/LICENSE %{buildroot}/usr/share/package-licenses/pypi-rapidfuzz/9381ed95491683f531bb1582ca99dcd805e35bf4 || :
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-rapidfuzz/0375d56b18430f366cea90f3712664ccd180558c
/usr/share/package-licenses/pypi-rapidfuzz/9381ed95491683f531bb1582ca99dcd805e35bf4
/usr/share/package-licenses/pypi-rapidfuzz/943137af74d8ef1313354a6a6de0a4dc3ee4df8c

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
